# StockTrade24.com
# 한국투자증권 API 자동매매 설정 파일
# 최종수정일: 2024.11.23

# ====== API 인증 정보 ======
# 한국투자증권 웹페이지에서 API 서비스 신청시 발급받은 키값들입니다.
# [마이페이지] -> [Open API] -> [사용자 API 신청/조회]에서 확인 가능합니다.
APP_KEY: ""        # 발급받은 API 앱키를 입력하세요
APP_SECRET: ""     # 발급받은 API 시크릿키를 입력하세요

# ====== 계좌 정보 ======
# 한국투자증권 계좌번호를 입력합니다. 
# 계좌번호는 총 10자리이며, 앞 8자리와 뒤 2자리를 분리해서 입력합니다.
CANO: ""           # 계좌번호 앞 8자리를 입력하세요
ACNT_PRDT_CD: "01" # 계좌번호 뒤 2자리 (보통 "01"입니다)

# ====== API 서버 설정 ======
# 실전/모의투자 구분을 위한 서버 URL입니다.
# 실전투자와 모의투자는 서로 다른 URL을 사용합니다.

# 실전투자용 서버 URL (실제 계좌로 매매시 사용)
URL_BASE: "https://openapi.koreainvestment.com:9443"

# 모의투자용 서버 URL (테스트용)
# URL_BASE: "https://openapivts.koreainvestment.com:29443"
# 모의투자를 사용하려면 위 주석을 해제하고, 실전투자 URL을 주석처리 하세요.

# ====== 알림 설정 ======
# 매매 결과 및 에러를 디스코드로 받아보기 위한 설정입니다.
# 디스코드 채널에서 웹훅 URL을 생성하여 입력하세요.
DISCORD_WEBHOOK_URL: ""  # 디스코드 웹훅 URL을 입력하세요
